### PR TITLE
Rest for 0.1 version

### LINKED ISSUE #29: Setup coverage

### PR DESCRIPTION
**Pull request by pradel**
Prepare rest-express for 0.1 version
Close #29

### CODE REVIEW

**Comment by pradel** [comment]
The coverage is now 100% for the rest-client and rest-express packages 🎉

**Comment by pradel** [comment]
I renamed loginWithPassword by loginWithService, now password logins have to be called like that:
```javascript
 await client.loginWithService('password', {
        user: {
          username: 'toto',
        },
        password: 'password',
      });
```

**Comment by dotansimha** [comment]
@davidyaha can we merge?

**Comment by pradel** [comment]
@dotansimha same here we will need to wait the main pr to be merged before

**Pull request merged**
